### ISSUE TITLE
App does not install on Android 11

### ISSUE THREAD

**Issue by pusherplayer** [BibleNotify/BibleNotify#3]
I tried to install this on my android 11 phone on fdroid and it gives me this error
"could not validate Bible Notify
invalid file format"

**Comment by Correct-Syntax** [comment]
Hi, @pusherplayer I am not sure if the app has been released on f-droid yet. Could you try the .apk from https://github.com/BibleNotify/BibleNotify/releases/tag/v3.0 to see if that works. 🙂

**Comment by pusherplayer** [comment]
![Screenshot_20211026-223524](https://user-images.githubusercontent.com/49151242/138964470-3ad4b0fa-5058-4a7e-8fee-dfe337d70889.png)
@Correct-Syntax I tried that as well it gives me app not installed

**Comment by Correct-Syntax** [comment]
@pusherplayer thanks for trying that. I just tried installing the .apk on my Android 10 phone and it works. Perhaps you didn't give permission to "install apps from unknown sources" in the settings? Otherwise, I am not sure what the issue could be.

@sundrycode do you have any ideas?

**Comment by pusherplayer** [comment]
@Correct-Syntax I used an app manager to scan the apk and it gave me this 

![Screenshot_20211026-224220](https://user-images.githubusercontent.com/49151242/138973025-e56c4bdd-3d4c-42d6-bf2e-ae439b7cb4ad.png)
Could this be the issue

**Comment by Correct-Syntax** [comment]
@pusherplayer yes, that is likely the issue. The app was tested up to Android 10 but not signed in the way that Android 11+ requires.

We will make another release with the apk signed correctly for Android 11. 

Until then, thanks for your patience and interest in Bible Notify. 🙂

**Comment by pusherplayer** [comment]
@Correct-Syntax Thanks for the help

**Comment by Correct-Syntax** [comment]
@pusherplayer the latest release at https://github.com/BibleNotify/BibleNotify/releases/tag/v3.1 should fix the issue.

Feel free to re-open this issue if the app still doesn't work.
